/**
 * Hexo Theme Claude - Client-Side Search Engine
 * Searches against /search.json or /search.xml generated by Hexo
 */

(function () {
  'use strict';

  let searchDatabase = null;
  let isLoading = false;

  const loadSearchDatabase = async (searchPath) => {
    if (searchDatabase || isLoading) return;
    isLoading = true;

    try {
      const response = await fetch(searchPath);
      if (!response.ok) throw new Error('Failed to load search data');
      searchDatabase = await response.json();
    } catch (err) {
      console.warn('Search index not available or failed to load:', err);
    } finally {
      isLoading = false;
    }
  };

  const highlightText = (text, query) => {
    if (!query) return text;
    const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
    return text.replace(regex, '<span style="color: var(--brand); font-weight: 600;">$1</span>');
  };

  const resultMessage = (text) =>
    `<div style="padding: 1rem; text-align: center; color: var(--text-muted); font-size: 0.8125rem;">${text}</div>`;

  document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.getElementById('search-input');
    const searchResults = document.getElementById('search-results');
    const searchModal = document.getElementById('search-modal');
    const searchPath = searchInput ? searchInput.getAttribute('data-search-path') || '/search.json' : '/search.json';

    if (!searchInput || !searchResults) return;

    const i18n = searchModal ? searchModal.dataset : {};
    const MSG_HINT = i18n.i18nHint || 'Type to search...';
    const MSG_EMPTY = i18n.i18nEmpty || 'No search index available';
    const MSG_NO_RESULTS = i18n.i18nNoResults || 'No matching articles found';

    // Preload search data on focus or hover
    searchInput.addEventListener('focus', () => loadSearchDatabase(searchPath));

    searchInput.addEventListener('input', async (e) => {
      const query = e.target.value.trim().toLowerCase();

      if (!searchDatabase) {
        await loadSearchDatabase(searchPath);
      }

      if (!query) {
        searchResults.innerHTML = resultMessage(MSG_HINT);
        return;
      }

      if (!searchDatabase || searchDatabase.length === 0) {
        searchResults.innerHTML = resultMessage(MSG_EMPTY);
        return;
      }

      const results = searchDatabase.filter(item => {
        const title = (item.title || '').toLowerCase();
        const content = (item.content || '').toLowerCase();
        const tags = (item.tags || []).join(' ').toLowerCase();
        const categories = (item.categories || []).join(' ').toLowerCase();

        return title.includes(query) || content.includes(query) || tags.includes(query) || categories.includes(query);
      }).slice(0, 10);

      if (results.length === 0) {
        searchResults.innerHTML = resultMessage(MSG_NO_RESULTS);
        return;
      }

      searchResults.innerHTML = results.map(item => {
        let snippet = item.content ? item.content.replace(/<[^>]+>/g, '').trim() : '';
        const idx = snippet.toLowerCase().indexOf(query);
        if (idx !== -1) {
          const start = Math.max(0, idx - 40);
          const end = Math.min(snippet.length, idx + 80);
          snippet = (start > 0 ? '...' : '') + snippet.substring(start, end) + (end < snippet.length ? '...' : '');
        } else {
          snippet = snippet.substring(0, 90) + (snippet.length > 90 ? '...' : '');
        }

        return `
          <a href="${item.url}" class="search-result-item">
            <div class="item-title">${highlightText(item.title, query)}</div>
            ${snippet ? `<div class="item-snippet">${highlightText(snippet, query)}</div>` : ''}
          </a>
        `;
      }).join('');
    });
  });
})();
